version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - database
      - default

  postgres:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80

volumes:
  postgres:
    driver: local

networks:
  database: